# Site settings
title: Rafter Home Improvements
description: "Rafter Home Improvements"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

#Sass settings
sass:
sass_dir: css
style: :compressed
